name: Test
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and Test
      run: mvn -B clean package